DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  walletaddress TEXT UNIQUE NOT NULL,
  minimumbalance INTEGER NOT NULL,
  maximumbalance INTEGER NOT NULL,
  factor float DEFAULT 2.0
);